services:
  tag-management-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tag-management-demo
    ports:
      - "8080:8080"
    volumes:
      - ./h2data:/data
    environment:
      SPRING_H2_CONSOLE_ENABLED: "true"
    restart: unless-stopped
